In [70]:
import numpy as np
import pandas as pd
from sklearn import model_selection

In [71]:
test_values=np.loadtxt("test_ccpp_x_test.csv",delimiter=',')
#change if want to change anything in this 


#til this if any
df=pd.DataFrame(test_values)
df[4]=1
finaltest=df.values
finaltest.shape

(2392, 5)

In [94]:
#for finding the train data 

train_inputs=np.loadtxt("training_ccpp_x_y_train.csv",delimiter=',')
#print(train_inputs)
y=train_inputs[:,train_inputs.shape[1]-1]
x=train_inputs[:,0:train_inputs.shape[1]-1]

print(x)
#print("\n************The output for training data is************ \n",y[0][0])


[[    8.58    38.38  1021.03    84.37]
 [   21.79    58.2   1017.21    66.74]
 [   16.64    48.92  1011.55    78.76]
 ..., 
 [   29.8     69.34  1009.36    64.74]
 [   16.37    54.3   1017.94    63.63]
 [   30.11    62.04  1010.69    47.96]]


In [95]:
#printiing the values of x and y as a trained data
#print(x,"\n",y)
#print('\n',x.shape," ",y.shape)
df=pd.DataFrame(x)
df[4]=1
x=df.values
x.shape

(7176, 5)

In [96]:
m_values=(np.zeros(x.shape[1])).reshape(-1,1)
m_values
print(df.head())
print(np.dot(x,m_values))

       0      1        2      3  4
0   8.58  38.38  1021.03  84.37  1
1  21.79  58.20  1017.21  66.74  1
2  16.64  48.92  1011.55  78.76  1
3  31.38  71.32  1009.17  60.42  1
4   9.20  40.03  1017.05  92.46  1
[[ 0.]
 [ 0.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]


In [97]:
def cof(x,y,final_m):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-97-38676495f5d2>, line 2)

In [98]:
def cost(x,y,m_values):
    total=0
    for i in range(len(x)):
        total=total+(1/len(x))*( ( y[i] - ( np.dot( x[i,:],m_values ) ).sum() )**2 )
        
    return total 

In [107]:
def gd(rate,iteration,x,y):
    m_values=(np.zeros(x.shape[1])).reshape(-1,1)
    
    for i in range(iteration):
        m_values=single_gradient(rate,m_values,x,y)
        print(i," cost is ",cost(x,y,m_values))
        
    return m_values

In [108]:
def single_gradient(rate,m_values,x,y):
    m_slope=(np.zeros(x.shape[1]).reshape(-1,1))
    m=len(x)
    
    for i in range(len(x)):
        row=x[i,:]
        for j in range(len(m_values)):
            m_slope[j]+=(-2/m)*(y[i]-np.dot(row,m_values).sum())*row[j]
    
    return m_values-rate*m_slope
    

In [109]:
def run():
    rate=.000001
    iteration=100
    final_m=gd(rate,iteration,x,y)
    
    yfinal=np.zeros(len(finaltest))
    yfinal=yfinal.reshape(-1,1)
    
    print(" the value of final m is \n", final_m)
    for i in range(len(finaltest)):
        yfinal[i]=(np.dot(finaltest[i],final_m).sum())    
        
#coefficent( x,y,final_m)

    np.savetxt("project1ans.csv",yfinal,delimiter=',',fmt='%1.5f')

In [110]:
run()

0  cost is  237116.915348
1  cost is  271882.125577
2  cost is  311750.087872
3  cost is  357469.767024
4  cost is  409900.058364
5  cost is  470025.922994
6  cost is  538976.891305
7  cost is  618048.282366
8  cost is  708725.537832
9  cost is  812712.127501
10  cost is  931961.550751
11  cost is  1068714.03504
12  cost is  1225538.6209
13  cost is  1405381.42401
14  cost is  1611620.98101
15  cost is  1848131.71883
16  cost is  2119356.73977
17  cost is  2430391.28978
18  cost is  2787078.4779
19  cost is  3196119.04512
20  cost is  3665197.24471
21  cost is  4203125.19883
22  cost is  4820008.44338
23  cost is  5527435.77088
24  cost is  6338696.93796
25  cost is  7269032.32709
26  cost is  8335919.25296
27  cost is  9559400.29187
28  cost is  10962459.8022
29  cost is  12571455.7093
30  cost is  14416614.6663
31  cost is  16532599.8932
32  cost is  18959162.361
33  cost is  21741887.5548
34  cost is  24933051.8443
35  cost is  28592604.5493
36  cost is  32789294.1494
37  cost is  3